function    ImgRGB = ycbcr_2_rgb( ImgYCbCr )
% Assumes on input Y between 0:255, U/V between -128:127
% Outputs R/G/B between 0:255

ImgRGB(:,:,1) = ImgYCbCr(:,:,1)                           + 1.40200*ImgYCbCr(:,:,3);
ImgRGB(:,:,2) = ImgYCbCr(:,:,1) - 0.34414*ImgYCbCr(:,:,2) - 0.71414*ImgYCbCr(:,:,3);
ImgRGB(:,:,3) = ImgYCbCr(:,:,1) + 1.77200*ImgYCbCr(:,:,2)                          ;

% YCBCR2RGB = [1  0        1.40200; ...
%              1 -0.34414 -0.71414; ...
%              1  1.77200  0      ];
%           
% ImgRGB(:,:,1) = round( reshape( YCBCR2RGB(1,:) * ...
%                                     [reshape(ImgYCbCr(:,:,1),1,size(ImgYCbCr,1)*size(ImgYCbCr,2));        ...
%                                      reshape(ImgYCbCr(:,:,2),1,size(ImgYCbCr,1)*size(ImgYCbCr,2)) - 128;  ...
%                                      reshape(ImgYCbCr(:,:,3),1,size(ImgYCbCr,1)*size(ImgYCbCr,2)) - 128], ...
%                                  size(ImgYCbCr,1), size(ImgYCbCr,2) ) );
% 
% ImgRGB(:,:,2) = round( reshape( YCBCR2RGB(2,:) * ...
%                                     [reshape(ImgYCbCr(:,:,1),1,size(ImgYCbCr,1)*size(ImgYCbCr,2));        ...
%                                      reshape(ImgYCbCr(:,:,2),1,size(ImgYCbCr,1)*size(ImgYCbCr,2)) - 128;  ...
%                                      reshape(ImgYCbCr(:,:,3),1,size(ImgYCbCr,1)*size(ImgYCbCr,2)) - 128], ...
%                                  size(ImgYCbCr,1), size(ImgYCbCr,2) ) );
% 
% ImgRGB(:,:,3) = round( reshape( YCBCR2RGB(3,:) * ...
%                                     [reshape(ImgYCbCr(:,:,1),1,size(ImgYCbCr,1)*size(ImgYCbCr,2));        ...
%                                      reshape(ImgYCbCr(:,:,2),1,size(ImgYCbCr,1)*size(ImgYCbCr,2)) - 128;  ...
%                                      reshape(ImgYCbCr(:,:,3),1,size(ImgYCbCr,1)*size(ImgYCbCr,2)) - 128], ...
%                                  size(ImgYCbCr,1), size(ImgYCbCr,2) ) );


