%% Ron example - Equivalent
close all
clear classes
obj = SimplePipe(   'rawfile',          'imx105_v85_259.raw', ...
                    'Mode',             'BRCM10', ...
                    'Enable_Clipper',   false, ...
                    'Enable_CCM',       false, ...
                    'Enable_Gamma',     false, ...
                    'Enable_Saturation',false, ...
                    'Enable_Contrast',  false, ...
                    'BL',               64, ...
                    'DG',               4);
obj.RUN();
imageShow('imageOUT',obj.OutputEncoder_OBJ.imageOUT)

%%
ObjectInspector(obj)

%% DLS clipping Issue - Ron example
close all
clear classes
obj = SimplePipe(   'rawfile',          'IMG_20130923_121257.raw', ...
                    'Mode',             'BRCM16', ...
                    'Enable_Clipper',   false, ...
                    'Enable_CCM',       false, ...
                    'Enable_Gamma',     false, ...
                    'Enable_Saturation',false, ...
                    'Enable_Contrast',  false, ...
                    'BL',               2, ...
                    'DG',               4);
obj.RUN();
imageShow('imageOUT',obj.OutputEncoder_OBJ.imageOUT)

%% DLS clipping Issue - Ron example
close all
clear classes
obj = SimplePipe(   'rawfile',          'IMG_20130923_121257.raw', ...
                    'Mode',             'BRCM16', ...
                    'Enable_Clipper',   true, ...
                    'Enable_CCM',       true, ...
                    'Enable_Gamma',     true, ...
                    'Enable_Saturation',true, ...
                    'Enable_Contrast',  true, ...
                    'BL',               2, ...
                    'DG',               1);
obj.RUN();
imageShow('imageOUT',obj.OutputEncoder_OBJ.imageOUT)