function [ImgDat, FaceDat]=InitXlsStruct()

ImgDat.FileName=[];
ImgDat.Dir=[];
ImgDat.SizeX=[];
ImgDat.SizeY=[];
ImgDat.ThumbFile=[];
ImgDat.ThumbDir=[];
ImgDat.ThumbX=[];
ImgDat.ThumbY=[];
ImgDat.NoOfFaces=[];
ImgDat.SmlThumbFile=[];
ImgDat.SmlThumbX=[];
ImgDat.SmlThumbY=[];
ImgDat.SmlThumbDir=[];

            
FaceDat.FileName=[];
FaceDat.Dir=[];
FaceDat.SizeX=[];
FaceDat.SizeY=[];
FaceDat.ThumbFile=[];
FaceDat.ThumbDir=[];
FaceDat.ThumbX=[];
FaceDat.ThumbY=[];
FaceDat.SmlThumbFile=[];
FaceDat.SmlThumbX=[];
FaceDat.SmlThumbY=[];
FaceDat.SmlThumbDir=[];

FaceDat.FaceBoxRelX=[];
FaceDat.FaceBoxRelY=[];
FaceDat.FaceBoxRelW=[];
FaceDat.FaceBoxRelH=[];
FaceDat.FaceBoxX=[];
FaceDat.FaceBoxY=[];
FaceDat.FaceBoxW=[];
FaceDat.FaceBoxH=[];
FaceDat.RightEyeRelX=[];
FaceDat.RightEyeRelY=[];
FaceDat.RightEyeX=[];
FaceDat.RightEyeY=[];
FaceDat.LeftEyeRelX=[];
FaceDat.LeftEyeRelY=[];
FaceDat.LeftEyeX=[];
FaceDat.LeftEyeY=[];
FaceDat.MouthRelX=[];
FaceDat.MouthRelY=[];
FaceDat.MouthX=[];
FaceDat.MouthY=[];
FaceDat.Conf=[];
FaceDat.Pan=[];
FaceDat.FaceQuality=[];